version: 0.0
os: linux
files:
  - source: app.js
    destination: /var/www/bu-calendar-import
  - source: package.json
    destination: /var/www/bu-calendar-import
  - source: bin
    destination: /var/www/bu-calendar-import/bin
  - source: public
    destination: /var/www/bu-calendar-import/public
  - source: routes
    destination: /var/www/bu-calendar-import/routes
  - source: scripts
    destination: /var/www/bu-calendar-import/scripts
  - source: views
    destination: /var/www/bu-calendar-import/views

hooks:
  ApplicationStop:
    - location: scripts/stop_bu_cal
      runas: root
  AfterInstall:
    - location: scripts/reinstall_npm
      runas: root
  ApplicationStart:
    - location: scripts/restart_bu_cal
      runas: root
